import { Cocktail } from "../types/Cocktail";

export const favoriteCocktails: Cocktail[] = [
  {
    idDrink: "11014",
    strDrink: "Alexander",
    strDrinkAlternate: null,
    strTags: "IBA,Classic,Dairy",
    strCategory: "Ordinary Drink",
    strIBA: "Unforgettables",
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Shake all ingredients with ice and strain contents into a cocktail glass. Sprinkle nutmeg on top and serve.",
    strInstructionsES:
      "Agite todos los ingredientes con hielo y cuele el contenido en una copa de cóctel. Espolvorear nuez moscada por encima y servir.",
    strInstructionsDE:
      "Alle Zutaten mit Eis schütteln und in ein Cocktailglas abseihen. Muskatnuss darüber streuen und servieren.",
    strInstructionsFR:
      "Secouer tous les ingrédients avec de la glace et filtrer le contenu dans un verre à cocktail. Saupoudrer de noix de muscade et servir.",
    strInstructionsIT:
      "Shakerare tutti gli ingredienti con ghiaccio e filtrare il contenuto in un bicchiere da cocktail. Cospargere di noce moscata e servire.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/0clus51606772388.jpg",
    strIngredient1: "Gin",
    strIngredient2: "Creme de Cacao",
    strIngredient3: "Light cream",
    strIngredient4: "Nutmeg",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1/2 oz ",
    strMeasure2: "1/2 oz white ",
    strMeasure3: "2 oz ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2016-11-04 09:50:39",
  },
  {
    idDrink: "11001",
    strDrink: "Old Fashioned",
    strDrinkAlternate: null,
    strTags: "IBA,Classic,Savory",
    strCategory: "Cocktail",
    strIBA: "Unforgettables",
    strAlcoholic: "Alcoholic",
    strGlass: "Old-fashioned glass",
    strInstructions:
      "Place sugar cube in old fashioned glass and saturate with bitters, add a dash of plain water. Muddle until dissolved.\r\nFill the glass with ice cubes and add whiskey.\r\n\r\nGarnish with orange twist, and a cocktail cherry.",
    strInstructionsES:
      "Ponga el terr\u00f3n de az\u00facar en un vaso old fashioned y \u00fantelo con el amargo, a\u00f1ada un chorrito de agua. Mezcle hasta que se disuelva.\r\nLlene el vaso con cubitos de hielo y a\u00f1ada whisky.\r\n\r\nDecorar con un twist de naranja y una cereza de c\u00f3ctel.",
    strInstructionsDE:
      "Zuckerw\u00fcrfel in ein old fashioned Glas geben und mit Bitterstoff s\u00e4ttigen, einen Schuss Wasser hinzuf\u00fcgen. Vermischen, bis sie sich aufl\u00f6sen.",
    strInstructionsFR:
      "Placer un morceau de sucre dans un verre \u00e0 l'ancienne et l'imbiber d'amers, ajouter un trait d'eau plate. M\u00e9langer jusqu'\u00e0 dissolution.\r\nRemplir le verre de gla\u00e7ons et ajouter le whisky.\r\n\r\nGarnir d'un zeste d'orange et d'une cerise \u00e0 cocktail.",
    strInstructionsIT:
      "Mettere la zolletta di zucchero nel bicchiere vecchio stile e saturare con il bitter, aggiungere un goccio di acqua naturale.\r\nPestare finch\u00e9 non si scioglie.\r\nRiempi il bicchiere con cubetti di ghiaccio e aggiungi il whisky.\r\nGuarnire con una scorza d'arancia e una ciliegina al maraschino.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/vrwquq1478252802.jpg",
    strIngredient1: "Bourbon",
    strIngredient2: "Angostura bitters",
    strIngredient3: "Sugar",
    strIngredient4: "Water",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "4.5 cL",
    strMeasure2: "2 dashes",
    strMeasure3: "1 cube",
    strMeasure4: "dash",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2016-11-04 09:46:42",
  },

  {
    idDrink: "17194",
    strDrink: "White Lady",
    strDrinkAlternate: null,
    strTags: "IBA,Classic",

    strCategory: "Ordinary Drink",
    strIBA: "Unforgettables",
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Add all ingredients into cocktail shaker filled with ice. Shake well and strain into large cocktail glass.",
    strInstructionsES: null,
    strInstructionsDE:
      "Alle Zutaten in den mit Eis gef\u00fcllten Cocktailshaker geben. Gut sch\u00fctteln und in ein gro\u00dfes Cocktailglas abseihen.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Aggiungere tutti gli ingredienti in uno shaker pieno di ghiaccio.Shakerare bene e filtrare in una coppetta da cocktail grande.",

    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/jofsaz1504352991.jpg",
    strIngredient1: "Gin",
    strIngredient2: "Triple Sec",
    strIngredient3: "Lemon Juice",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "4cl",
    strMeasure2: "3cl",
    strMeasure3: "2cl",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2017-09-02 12:49:52",
  },
];
