import { Cocktail } from "../types/Cocktail";

export const initialCocktails: Cocktail[] = [
  {
    idDrink: "11014",
    strDrink: "Alexander",
    strDrinkAlternate: null,
    strTags: "IBA,Classic,Dairy",
    strCategory: "Ordinary Drink",
    strIBA: "Unforgettables",
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Shake all ingredients with ice and strain contents into a cocktail glass. Sprinkle nutmeg on top and serve.",
    strInstructionsES:
      "Agite todos los ingredientes con hielo y cuele el contenido en una copa de cóctel. Espolvorear nuez moscada por encima y servir.",
    strInstructionsDE:
      "Alle Zutaten mit Eis schütteln und in ein Cocktailglas abseihen. Muskatnuss darüber streuen und servieren.",
    strInstructionsFR:
      "Secouer tous les ingrédients avec de la glace et filtrer le contenu dans un verre à cocktail. Saupoudrer de noix de muscade et servir.",
    strInstructionsIT:
      "Shakerare tutti gli ingredienti con ghiaccio e filtrare il contenuto in un bicchiere da cocktail. Cospargere di noce moscata e servire.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/0clus51606772388.jpg",
    strIngredient1: "Gin",
    strIngredient2: "Creme de Cacao",
    strIngredient3: "Light cream",
    strIngredient4: "Nutmeg",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1/2 oz ",
    strMeasure2: "1/2 oz white ",
    strMeasure3: "2 oz ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2016-11-04 09:50:39",
  },
  {
    idDrink: "11001",
    strDrink: "Old Fashioned",
    strDrinkAlternate: null,
    strTags: "IBA,Classic,Savory",
    strCategory: "Cocktail",
    strIBA: "Unforgettables",
    strAlcoholic: "Alcoholic",
    strGlass: "Old-fashioned glass",
    strInstructions:
      "Place sugar cube in old fashioned glass and saturate with bitters, add a dash of plain water. Muddle until dissolved.\r\nFill the glass with ice cubes and add whiskey.\r\n\r\nGarnish with orange twist, and a cocktail cherry.",
    strInstructionsES:
      "Ponga el terr\u00f3n de az\u00facar en un vaso old fashioned y \u00fantelo con el amargo, a\u00f1ada un chorrito de agua. Mezcle hasta que se disuelva.\r\nLlene el vaso con cubitos de hielo y a\u00f1ada whisky.\r\n\r\nDecorar con un twist de naranja y una cereza de c\u00f3ctel.",
    strInstructionsDE:
      "Zuckerw\u00fcrfel in ein old fashioned Glas geben und mit Bitterstoff s\u00e4ttigen, einen Schuss Wasser hinzuf\u00fcgen. Vermischen, bis sie sich aufl\u00f6sen.",
    strInstructionsFR:
      "Placer un morceau de sucre dans un verre \u00e0 l'ancienne et l'imbiber d'amers, ajouter un trait d'eau plate. M\u00e9langer jusqu'\u00e0 dissolution.\r\nRemplir le verre de gla\u00e7ons et ajouter le whisky.\r\n\r\nGarnir d'un zeste d'orange et d'une cerise \u00e0 cocktail.",
    strInstructionsIT:
      "Mettere la zolletta di zucchero nel bicchiere vecchio stile e saturare con il bitter, aggiungere un goccio di acqua naturale.\r\nPestare finch\u00e9 non si scioglie.\r\nRiempi il bicchiere con cubetti di ghiaccio e aggiungi il whisky.\r\nGuarnire con una scorza d'arancia e una ciliegina al maraschino.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/vrwquq1478252802.jpg",
    strIngredient1: "Bourbon",
    strIngredient2: "Angostura bitters",
    strIngredient3: "Sugar",
    strIngredient4: "Water",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "4.5 cL",
    strMeasure2: "2 dashes",
    strMeasure3: "1 cube",
    strMeasure4: "dash",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2016-11-04 09:46:42",
  },
  {
    idDrink: "11000",
    strDrink: "Mojito",
    strDrinkAlternate: null,
    strTags: "IBA,Citrus",
    strCategory: "Cocktail",
    strIBA: "Contemporary Classics",
    strAlcoholic: "Alcoholic",
    strGlass: "Highball glass",
    strInstructions:
      "Muddle mint leaves with sugar and lime juice. Add a splash of soda water and fill the glass with cracked ice. Pour the rum and top with soda water. Garnish and serve with straw.",
    strInstructionsES:
      "Mezcle las hojas de menta con el az\u00facar y el zumo de lima. A\u00f1ada un chorrito de soda y llene el vaso con hielo picado. Verter el ron y completar con soda. Decorar y servir con pajita.",
    strInstructionsDE:
      "Minzbl\u00e4tter mit Zucker und Limettensaft verr\u00fchren. F\u00fcge einen Spritzer Sodawasser hinzu und f\u00fclle das Glas mit gebrochenem Eis. Den Rum eingie\u00dfen und mit Sodawasser \u00fcbergie\u00dfen. Garnieren und mit einem Strohhalm servieren.",
    strInstructionsFR:
      "M\u00e9langer les feuilles de menthe avec le sucre et le jus de citron vert. Ajoutez un filet d'eau gazeuse et remplissez le verre de glace concass\u00e9e. Verser le rhum et compl\u00e9ter avec de l'eau gazeuse. D\u00e9corer et servir avec une paille.",
    strInstructionsIT:
      "Pestare le foglie di menta con lo zucchero e il succo di lime.\r\nAggiungere una spruzzata di acqua di seltz e riempi il bicchiere con ghiaccio tritato.\r\nVersare il rum e riempire con acqua di seltz.\r\nGuarnire con una fetta di lime, servire con una cannuccia.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/metwgh1606770327.jpg",
    strIngredient1: "Light rum",
    strIngredient2: "Lime",
    strIngredient3: "Sugar",
    strIngredient4: "Mint",
    strIngredient5: "Soda water",
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2-3 oz ",
    strMeasure2: "Juice of 1 ",
    strMeasure3: "2 tsp ",
    strMeasure4: "2-4 ",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2016-11-04 09:17:09",
  },
  {
    idDrink: "11005",
    strDrink: "Dry Martini",
    strDrinkAlternate: null,
    strTags: "IBA,Classic,Christmas",
    strCategory: "Cocktail",
    strIBA: "Unforgettables",
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Straight: Pour all ingredients into mixing glass with ice cubes. Stir well. Strain in chilled martini cocktail glass. Squeeze oil from lemon peel onto the drink, or garnish with olive.",
    strInstructionsES:
      "Derecho: Vierta todos los ingredientes en un vaso mezclador con cubitos de hielo. Remover bien. Colar en una copa de martini fr\u00eda. Exprima el aceite de la c\u00e1scara de lim\u00f3n sobre la bebida, o decore con aceitunas.",
    strInstructionsDE:
      "Pur: Alle Zutaten mit Eisw\u00fcrfeln in ein R\u00fchrglas geben. Gut umr\u00fchren. In ein gek\u00fchltes Martini-Cocktailglas abseihen. Dr\u00fccken Sie das \u00d6l aus der Zitronenschale auf das Getr\u00e4nk oder garnieren Sie es mit Oliven.",
    strInstructionsFR:
      "Droit : Verser tous les ingr\u00e9dients dans un verre \u00e0 m\u00e9lange avec des gla\u00e7ons. Bien m\u00e9langer. Filtrer dans un verre \u00e0 cocktail martini r\u00e9frig\u00e9r\u00e9. Presser l'huile du zeste de citron sur la boisson ou d\u00e9corer d'une olive.",
    strInstructionsIT:
      "Dritto: Versare tutti gli ingredienti nel mixing glass con cubetti di ghiaccio. Mescolare bene. Filtrare in una coppetta da cocktail Martini ghiacciata. Spremi l'olio della scorza di limone sulla bevanda o guarnisci con l'oliva.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/6ck9yi1589574317.jpg",
    strIngredient1: "Gin",
    strIngredient2: "Dry Vermouth",
    strIngredient3: "Olive",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 2/3 oz ",
    strMeasure2: "1/3 oz ",
    strMeasure3: "1 ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2017-09-02 12:51:35",
  },
  {
    idDrink: "17196",
    strDrink: "Cosmopolitan",
    strDrinkAlternate: null,
    strTags: "IBA,ContemporaryClassic",
    strCategory: "Cocktail",
    strIBA: "Contemporary Classics",
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Add all ingredients into cocktail shaker filled with ice. Shake well and double strain into large cocktail glass. Garnish with lime wheel.",
    strInstructionsES:
      "A\u00f1ada todos los ingredientes en una coctelera llena de hielo. Agite bien y cuele dos veces en una copa de c\u00f3ctel grande. Decorar con una rueda de lima.",
    strInstructionsDE:
      "Alle Zutaten in den mit Eis gef\u00fcllten Cocktailshaker geben. Gut sch\u00fctteln und doppelt in ein gro\u00dfes Cocktailglas abseihen. Mit Limettenrad garnieren.",
    strInstructionsFR:
      "Ajouter tous les ingr\u00e9dients dans un shaker rempli de glace. Bien agiter et filtrer dans un grand verre \u00e0 cocktail. Garnir d'une roue de citron vert.",
    strInstructionsIT:
      "Aggiungi tutti gli ingredienti in uno shaker pieno di ghiaccio.\r\nShakerare bene e filtrare due volte in una grande coppetta da cocktail.\r\nGuarnire con una fetta di lime.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/kpsajh1504368362.jpg",
    strIngredient1: "Vodka",
    strIngredient2: "Lime juice",
    strIngredient3: "Cointreau",
    strIngredient4: "Cranberry juice",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 1/4 oz ",
    strMeasure2: "1/4 oz ",
    strMeasure3: "1/4 oz ",
    strMeasure4: "1/4 cup ",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2017-09-02 17:06:02",
  },
  {
    idDrink: "11403",
    strDrink: "Gin And Tonic",
    strDrinkAlternate: null,
    strTags: null,
    strCategory: "Ordinary Drink",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Highball glass",
    strInstructions:
      "Pour the gin and the tonic water into a highball glass almost filled with ice cubes. Stir well. Garnish with the lime wedge.",
    strInstructionsES:
      "Vierta la ginebra y el agua t\u00f3nica en un vaso highball casi lleno de cubitos de hielo. Remover bien. Decorar con la rodaja de lima.",
    strInstructionsDE:
      "Gie\u00dfen Sie den Gin und das Tonic Water in ein Highball-Glas, das fast mit Eisw\u00fcrfeln gef\u00fcllt ist. Gut umr\u00fchren. Mit dem Limettenkeil garnieren.",
    strInstructionsFR:
      "Verser le gin et l'eau tonique dans un verre highball presque rempli de gla\u00e7ons. Bien m\u00e9langer. D\u00e9corer avec le quartier de citron vert.",
    strInstructionsIT:
      "Versare il gin e l'acqua tonica in un bicchiere highball quasi riempito di cubetti di ghiaccio. Guarnire con lo spicchio di lime. Mescolare bene.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/k0508k1668422436.jpg",
    strIngredient1: "Gin",
    strIngredient2: "Tonic water",
    strIngredient3: "Lime",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2 oz ",
    strMeasure2: "5 oz ",
    strMeasure3: "1 ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2016-08-28 18:37:11",
  },
  {
    idDrink: "11009",
    strDrink: "Moscow Mule",
    strDrinkAlternate: null,
    strTags: "IBA,ContemporaryClassic",

    strCategory: "Punch / Party Drink",
    strIBA: "Contemporary Classics",
    strAlcoholic: "Alcoholic",
    strGlass: "Copper Mug",
    strInstructions:
      "Combine vodka and ginger beer in a highball glass filled with ice. Add lime juice. Stir gently. Garnish.",
    strInstructionsES:
      "Mezcle el vodka y la cerveza de jengibre en un vaso highball lleno de hielo. A\u00f1ada el zumo de lima. Remover suavemente. Decorar.",
    strInstructionsDE:
      "Mischen Sie Wodka und Ingwerbier in einem mit Eis gef\u00fcllten Highball-Glas. Limettensaft hinzuf\u00fcgen. Vorsichtig umr\u00fchren. Garnieren.",
    strInstructionsFR:
      "M\u00e9langer la vodka et la bi\u00e8re de gingembre dans un verre highball rempli de glace. Ajouter le jus de citron vert. Remuer doucement. Garnir.",
    strInstructionsIT:
      "Unisci la vodka e la ginger beer in un bicchiere highball pieno di ghiaccio.\r\nAggiungi il succo di lime.\r\nMescola delicatamente.",

    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/3pylqc1504370988.jpg",
    strIngredient1: "Vodka",
    strIngredient2: "Lime juice",
    strIngredient3: "Ginger ale",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2 oz ",
    strMeasure2: "2 oz ",
    strMeasure3: "8 oz ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2017-09-02 17:49:48",
  },
  {
    idDrink: "11007",
    strDrink: "Margarita",
    strDrinkAlternate: null,
    strTags: "IBA,ContemporaryClassic",

    strCategory: "Ordinary Drink",
    strIBA: "Contemporary Classics",
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Rub the rim of the glass with the lime slice to make the salt stick to it. Take care to moisten only the outer rim and sprinkle the salt on it. The salt should present to the lips of the imbiber and never mix into the cocktail. Shake the other ingredients with ice, then carefully pour into the glass.",
    strInstructionsES:
      "Frota el borde del vaso con la rodaja de lima para que la sal se adhiera a \u00e9l. Procure humedecer s\u00f3lo el borde exterior y espolvorear la sal sobre \u00e9l. La sal debe presentarse en los labios del imbibidor y nunca mezclarse en el c\u00f3ctel. Agite los dem\u00e1s ingredientes con hielo y vi\u00e9rtalos con cuidado en el vaso.",
    strInstructionsDE:
      "Reiben Sie den Rand des Glases mit der Limettenscheibe, damit das Salz daran haftet. Achten Sie darauf, dass nur der \u00e4u\u00dfere Rand angefeuchtet wird und streuen Sie das Salz darauf. Das Salz sollte sich auf den Lippen des Genie\u00dfers befinden und niemals in den Cocktail einmischen. Die anderen Zutaten mit Eis sch\u00fctteln und vorsichtig in das Glas geben.",
    strInstructionsFR:
      "Frotter le bord du verre avec la tranche de citron vert pour faire adh\u00e9rer le sel. Veillez \u00e0 n'humidifier que le bord ext\u00e9rieur et \u00e0 y saupoudrer le sel. Le sel doit se pr\u00e9senter aux l\u00e8vres du buveur et ne jamais se m\u00e9langer au cocktail. Secouez les autres ingr\u00e9dients avec de la glace, puis versez-les d\u00e9licatement dans le verre.",
    strInstructionsIT:
      "Strofina il bordo del bicchiere con la fetta di lime per far aderire il sale.\r\nAvere cura di inumidire solo il bordo esterno e cospargere di sale.\r\nIl sale dovrebbe presentarsi alle labbra del bevitore e non mescolarsi mai al cocktail.\r\nShakerare gli altri ingredienti con ghiaccio, quindi versarli delicatamente nel bicchiere.",

    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/5noda61589575158.jpg",
    strIngredient1: "Tequila",
    strIngredient2: "Triple sec",
    strIngredient3: "Lime juice",
    strIngredient4: "Salt",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 1/2 oz ",
    strMeasure2: "1/2 oz ",
    strMeasure3: "1 oz ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2015-08-18 14:42:59",
  },

  {
    idDrink: "13621",
    strDrink: "Tequila Sunrise",
    strDrinkAlternate: null,
    strTags: "IBA,ContemporaryClassic",

    strCategory: "Cocktail",
    strIBA: "Contemporary Classics",
    strAlcoholic: "Alcoholic",
    strGlass: "Highball glass",
    strInstructions:
      "Pour the tequila and orange juice into glass over ice. Add the grenadine, which will sink to the bottom. Stir gently to create the sunrise effect. Garnish and serve.",
    strInstructionsES: null,
    strInstructionsDE:
      "Den Tequila und den Orangensaft in ein Glas \u00fcber Eis gie\u00dfen. F\u00fcge die Grenadine hinzu, die auf den Boden sinken wird. R\u00fchren Sie sanft um, um den Sonnenaufgangseffekt zu erzeugen. Garnieren und servieren.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Versare la tequila e il succo d'arancia in un bicchiere con ghiaccio.\r\nAggiungere la granatina, che affonder\u00e0 sul fondo.\r\nMescola delicatamente per creare l'effetto alba.\r\nGuarnire e servire.",

    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/quqyqp1480879103.jpg",
    strIngredient1: "Tequila",
    strIngredient2: "Orange juice",
    strIngredient3: "Grenadine",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2 measures ",
    strMeasure2: null,
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2016-12-04 19:18:23",
  },
  {
    idDrink: "11008",
    strDrink: "Manhattan",
    strDrinkAlternate: null,
    strTags: "IBA,Classic,Alcoholic",
    strCategory: "Cocktail",
    strIBA: "Unforgettables",
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions: "Stirred over ice, strained into a chilled glass, garnished, and served up.",
    strInstructionsES: "Se remueve con hielo, se cuela en un vaso fr\u00edo, se adorna y se sirve.",
    strInstructionsDE: "\u00dcber Eis ger\u00fchrt, in ein gek\u00fchltes Glas geseiht, garniert und serviert.",
    strInstructionsFR: "Remuer avec de la glace, filtrer dans un verre r\u00e9frig\u00e9r\u00e9, garnir et servir.",
    strInstructionsIT: "Mescolate su ghiaccio, filtrate in un bicchiere freddo, guarnite e servite.",

    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/yk70e31606771240.jpg",
    strIngredient1: "Sweet Vermouth",
    strIngredient2: "Bourbon",
    strIngredient3: "Angostura bitters",
    strIngredient4: "Ice",
    strIngredient5: "Maraschino cherry",
    strIngredient6: "Orange peel",
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "3/4 oz ",
    strMeasure2: "2 1/2 oz Blended ",
    strMeasure3: "dash ",
    strMeasure4: "2 or 3 ",
    strMeasure5: "1 ",
    strMeasure6: "1 twist of ",
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2017-09-02 12:07:09",
  },
  {
    idDrink: "17194",
    strDrink: "White Lady",
    strDrinkAlternate: null,
    strTags: "IBA,Classic",

    strCategory: "Ordinary Drink",
    strIBA: "Unforgettables",
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Add all ingredients into cocktail shaker filled with ice. Shake well and strain into large cocktail glass.",
    strInstructionsES: null,
    strInstructionsDE:
      "Alle Zutaten in den mit Eis gef\u00fcllten Cocktailshaker geben. Gut sch\u00fctteln und in ein gro\u00dfes Cocktailglas abseihen.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Aggiungere tutti gli ingredienti in uno shaker pieno di ghiaccio.Shakerare bene e filtrare in una coppetta da cocktail grande.",

    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/jofsaz1504352991.jpg",
    strIngredient1: "Gin",
    strIngredient2: "Triple Sec",
    strIngredient3: "Lemon Juice",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "4cl",
    strMeasure2: "3cl",
    strMeasure3: "2cl",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2017-09-02 12:49:52",
  },
  {
    idDrink: "11121",
    strDrink: "Bobby Burns Cocktail",
    strDrinkAlternate: null,
    strTags: null,
    strCategory: "Ordinary Drink",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Stir all ingredients (except lemon peel) with ice and strain into a cocktail glass. Add the twist of lemon peel and serve.",
    strInstructionsES:
      "Remover todos los ingredientes (excepto la piel de limón) con hielo y colar en una copa de cóctel. Añadir el twist de piel de limón y servir.",
    strInstructionsDE:
      "Alle Zutaten (außer Zitronenschale) mit Eis verrühren und in ein Cocktailglas abseihen. Die Zitronenschale hinzufügen und servieren.",
    strInstructionsFR:
      "Mélanger tous les ingrédients (sauf le zeste de citron) avec de la glace et filtrer dans un verre à cocktail. Ajouter le zeste de citron et servir.",
    strInstructionsIT:
      "Aggiungere la scorza di limone e servire.Mescolare tutti gli ingredienti (tranne la buccia di limone) con ghiaccio e filtrare in una coppetta da cocktail.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/km6se51484411608.jpg",
    strIngredient1: "Sweet Vermouth",
    strIngredient2: "Scotch",
    strIngredient3: "Benedictine",
    strIngredient4: "Lemon peel",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 1/2 oz ",
    strMeasure2: "1 1/2 oz ",
    strMeasure3: "1 1/4 tsp ",
    strMeasure4: "1 twist of ",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2017-01-14 16:33:28",
  },
  {
    idDrink: "12758",
    strDrink: "Gagliardo",
    strDrinkAlternate: null,
    strTags: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Shake well and serve in a cocktail glass. This is a home cocktail of American/Internet Bar del Pozzo, Pavia, Italy.",
    strInstructionsES:
      "Agitar bien y servir en copa de cóctel. Este es un cóctel casero de American/Internet Bar del Pozzo, Pavia, Italia.",
    strInstructionsDE:
      "Gut schütteln und in einem Cocktailglas servieren. Dies ist ein Cocktail aus American/Internet Bar del Pozzo, Pavia, Italien.",
    strInstructionsFR:
      "Bien agiter et servir dans un verre à cocktail. Il s'agit d'un cocktail maison de l'Américain/Internet Bar del Pozzo, Pavie, Italie.",
    strInstructionsIT:
      "Shakerare bene e servire in una coppetta da cocktail.Questo è un cocktail casalingo dell'American / Internet Bar del Pozzo, Pavia, Italia.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/lyloe91487602877.jpg",
    strIngredient1: "Peach Vodka",
    strIngredient2: "Lemon juice",
    strIngredient3: "Galliano",
    strIngredient4: "Sirup of roses",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "5 parts ",
    strMeasure2: "3 parts ",
    strMeasure3: "1 part ",
    strMeasure4: "1 part ",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2017-02-20 15:01:18",
  },
  {
    idDrink: "12714",
    strDrink: "Kiwi Papaya Smoothie",
    strDrinkAlternate: null,
    strTags: null,
    strCategory: "Other / Unknown",
    strIBA: null,
    strAlcoholic: "Non alcoholic",
    strGlass: "Highball Glass",
    strInstructions: "Throw everything into a blender and liquify.",
    strInstructionsES: "Echar todo en una batidora y licuar.",
    strInstructionsDE: "Alles in einen Mixer geben und aufschlagen.",
    strInstructionsFR: "Mettre le tout dans un mixeur et liquéfier.",
    strInstructionsIT: "Getta tutto in un frullatore e liquida.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/jogv4w1487603571.jpg",
    strIngredient1: "Kiwi",
    strIngredient2: "Papaya",
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "3 ",
    strMeasure2: "1/2 ",
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2017-02-20 15:12:51",
  },
  {
    idDrink: "12774",
    strDrink: "Masala Chai",
    strDrinkAlternate: null,
    strTags: null,
    strCategory: "Coffee / Tea",
    strIBA: null,
    strAlcoholic: "Non alcoholic",
    strGlass: "Coffee Mug",
    strInstructions:
      "Bring 2 cups of water to boil. Add all the ingredients and boil again for about 15 seconds. Let stand for a minute. Warm milk in a pot. Filter tea into cups. Add milk and sugar. That's IT.",
    strInstructionsES:
      "Pon a hervir 2 tazas de agua. Agrega todos los ingredientes y vuelve a hervir durante unos 15 segundos. Dejar reposar por un minuto. Calienta la leche en una olla. Filtra el té en tazas. Agrega la leche y el azúcar. Eso es todo.",
    strInstructionsDE:
      "2 Tassen Wasser zum Kochen bringen. Alle Zutaten zugeben und nochmals ca. 15 Sekunden kochen lassen. Eine Minute stehen lassen. Milch in einem Topf erwärmen. Tee in Tassen filtern. Milch und Zucker hinzufügen. Servieren.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Porta ad ebollizione 2 tazze d'acqua.\r\nAggiungere tutti gli ingredienti e far bollire di nuovo per circa 15 secondi.\r\nLascia riposare per un minuto.\r\nLatte caldo in una pentola.\r\nFiltra il tè in tazze.\r\nAggiungere il latte e lo zucchero.\r\nQuesto è tutto.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/uyrpww1441246384.jpg",
    strIngredient1: "Water",
    strIngredient2: "Tea",
    strIngredient3: "Ginger",
    strIngredient4: "Cardamom",
    strIngredient5: "Cloves",
    strIngredient6: "Cinnamon",
    strIngredient7: "Black pepper",
    strIngredient8: "Sugar",
    strIngredient9: "Milk",
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2 cups ",
    strMeasure2: "3-4 tsp ",
    strMeasure3: "1 chunk dried ",
    strMeasure4: "3-4 crushed ",
    strMeasure5: "3 ",
    strMeasure6: "1 piece ",
    strMeasure7: "1-2 whole ",
    strMeasure8: " to taste\n",
    strMeasure9: "to taste",
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2015-09-03 03:13:04",
  },
  {
    idDrink: "13751",
    strDrink: "Cuba Libra",
    strDrinkAlternate: null,
    strTags: null,
    strCategory: "Ordinary Drink",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Highball glass",
    strInstructions:
      "Fill tall glass with ice cubes. Add rum. Rub cut edge of lime on rim of glass then squeeze juice into glass. Fill with Coca-Cola. Garnish with lime slice. Enjoy!",
    strInstructionsES:
      "Llene el vaso alto con cubitos de hielo. A\u00f1ada ron. Frote el borde cortado de la lima en el borde del vaso y, a continuaci\u00f3n, exprima el zumo en el vaso. Rellenar con Coca-Cola. Dec\u00f3ralo con una rodaja de lima. \u00a1Que aproveche!",
    strInstructionsDE:
      "F\u00fcllen Sie das hohe Glas mit Eisw\u00fcrfeln. F\u00fcge Rum hinzu. Reiben Sie die Schnittkante der Limette auf den Glasrand und dr\u00fccken Sie den Saft in das Glas. Mit Coca-Cola f\u00fcllen. Mit Limettenscheibe garnieren. Viel Spa\u00df!",
    strInstructionsFR:
      "Remplir le grand verre de gla\u00e7ons. Ajouter le rhum. Frotter le bord du verre avec le bord coup\u00e9 du citron vert, puis presser le jus dans le verre. Remplir de Coca-Cola. D\u00e9corer avec une tranche de citron vert. Savourez !",
    strInstructionsIT:
      "Riempi un bicchiere alto con cubetti di ghiaccio.\r\nAggiungi il rum.\r\nStrofinare il bordo tagliato di lime sul bordo del bicchiere, quindi spremere il succo in un bicchiere.\r\nRiempi di Coca-Cola.\r\nGuarnire con una fetta di lime.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/ck6d0p1504388696.jpg",
    strIngredient1: "Dark rum",
    strIngredient2: "Lime",
    strIngredient3: "Coca-Cola",
    strIngredient4: "Ice",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1-2 shot ",
    strMeasure2: "Squeeze ",
    strMeasure3: "Fill with ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2017-09-02 22:44:56",
  },
  {
    idDrink: "15825",
    strDrink: "Jamaican Coffee",
    strDrinkAlternate: null,
    strTags: null,
    strCategory: "Coffee / Tea",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Champagne flute",
    strInstructions:
      "Stir the rum, coffee and water together. Top with the whipped cream. Sprinkle with a pinch of well ground coffee and drink with a straw.",
    strInstructionsES: null,
    strInstructionsDE:
      "Rum, Kaffee und Wasser miteinander verr\u00fchren. Mit der geschlagenen Sahne bedecken. Mit einer Prise gut gemahlenem Kaffee bestreuen und mit einem Strohhalm trinken.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Mescola rum, caff\u00e8 e acqua insieme.\r\nCompletare con la panna montata.\r\nCospargere con un pizzico di caff\u00e8 ben macinato e bere con una cannuccia.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/xqptps1441247257.jpg",
    strIngredient1: "Rum",
    strIngredient2: "Coffee",
    strIngredient3: "Water",
    strIngredient4: "Whipped cream",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1/6 glass ",
    strMeasure2: "1/6 glass strong black ",
    strMeasure3: "1/2 glass cold ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2015-09-03 03:27:37",
  },
  {
    idDrink: "11002",
    strDrink: "Long Island Tea",
    strDrinkAlternate: null,
    strTags: "Strong,Asia,StrongFlavor,Brunch,Vegetarian,Sour",
    strCategory: "Ordinary Drink",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Highball glass",
    strInstructions:
      "Combine all ingredients (except cola) and pour over ice in a highball glass. Add the splash of cola for color. Decorate with a slice of lemon and serve.",
    strInstructionsES:
      "Mezcle todos los ingredientes (excepto el refresco de cola) y vi\u00e9rtalos sobre hielo en un vaso highball. A\u00f1ada el chorrito de cola para darle color. Decore con una rodaja de lim\u00f3n y sirva.",
    strInstructionsDE:
      "Alle Zutaten (au\u00dfer Cola) mischen und in einem Highball-Glas \u00fcber Eis gie\u00dfen. F\u00fcge einen Spritzer Cola hinzu, um Farbe zu erhalten. Mit einer Scheibe Zitrone dekorieren und servieren.",
    strInstructionsFR:
      "M\u00e9langer tous les ingr\u00e9dients (sauf le cola) et verser sur de la glace dans un verre highball. Ajoutez la goutte de cola pour donner de la couleur. D\u00e9corer avec une tranche de citron et servir.",
    strInstructionsIT:
      "Unisci tutti gli ingredienti (tranne la cola) e versa il ghiaccio in un bicchiere highball. Aggiungi la spruzzata di cola per il colore. Decorare con una fetta di limone e servire.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/nkwr4c1606770558.jpg",
    strIngredient1: "Vodka",
    strIngredient2: "Light rum",
    strIngredient3: "Gin",
    strIngredient4: "Tequila",
    strIngredient5: "Lemon",
    strIngredient6: "Coca-Cola",
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1/2 oz ",
    strMeasure2: "1/2 oz ",
    strMeasure3: "1/2 oz ",
    strMeasure4: "1/2 oz ",
    strMeasure5: "Juice of 1/2 ",
    strMeasure6: "1 splash ",
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2015-08-18 14:54:32",
  },
];
