import React, { useState } from "react";
import { Cocktail } from "../types/Cocktail";
import CocktailBord from "../components/CocktailBord";

// 初期カクテルデータ
const initialCocktails: Cocktail[] = [
  {
    idDrink: "16108",
    strDrink: "9 1/2 Weeks",
    strDrinkAlternate: null,
    strTags: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Combine all ingredients in glass mixer. Chill and strain into Cocktail glass. Garnish with sliced strawberry.",
    strInstructionsES:
      "Mezclar todos los ingredientes en una batidora de vaso. Enfríe y cuele en una copa de cóctel. Decorar con rodajas de fresa.",
    strInstructionsDE:
      "Alle Zutaten in einem Glasmischer vermengen. Abkühlen lassen und in das Cocktailglas abseihen. Mit Erdbeerscheiben garnieren.",
    strInstructionsFR:
      "Mélanger tous les ingrédients dans un mixeur. Refroidir et filtrer dans un verre à cocktail. Garnir de tranches de fraises.",
    strInstructionsIT:
      "Unisci tutti gli ingredienti in una planetaria.\r\nRaffredda e versa in un bicchiere da cocktail.\r\nGuarnire con la fragola a fette.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/xvwusr1472669302.jpg",
    strIngredient1: "Absolut Citron",
    strIngredient2: "Orange Curacao",
    strIngredient3: "Strawberry liqueur",
    strIngredient4: "Orange juice",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2 oz ",
    strMeasure2: "1/2 oz ",
    strMeasure3: "1 splash ",
    strMeasure4: "1 oz ",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2016-08-31 19:48:22",
  },
  {
    idDrink: "12714",
    strDrink: "Kiwi Papaya Smoothie",
    strDrinkAlternate: null,
    strTags: null,
    strCategory: "Other / Unknown",
    strIBA: null,
    strAlcoholic: "Non alcoholic",
    strGlass: "Highball Glass",
    strInstructions: "Throw everything into a blender and liquify.",
    strInstructionsES: "Echar todo en una batidora y licuar.",
    strInstructionsDE: "Alles in einen Mixer geben und aufschlagen.",
    strInstructionsFR: "Mettre le tout dans un mixeur et liquéfier.",
    strInstructionsIT: "Getta tutto in un frullatore e liquida.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/jogv4w1487603571.jpg",
    strIngredient1: "Kiwi",
    strIngredient2: "Papaya",
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "3 ",
    strMeasure2: "1/2 ",
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2017-02-20 15:12:51",
  },
  {
    idDrink: "12774",
    strDrink: "Masala Chai",
    strDrinkAlternate: null,
    strTags: null,
    strCategory: "Coffee / Tea",
    strIBA: null,
    strAlcoholic: "Non alcoholic",
    strGlass: "Coffee Mug",
    strInstructions:
      "Bring 2 cups of water to boil. Add all the ingredients and boil again for about 15 seconds. Let stand for a minute. Warm milk in a pot. Filter tea into cups. Add milk and sugar. That's IT.",
    strInstructionsES:
      "Pon a hervir 2 tazas de agua. Agrega todos los ingredientes y vuelve a hervir durante unos 15 segundos. Dejar reposar por un minuto. Calienta la leche en una olla. Filtra el té en tazas. Agrega la leche y el azúcar. Eso es todo.",
    strInstructionsDE:
      "2 Tassen Wasser zum Kochen bringen. Alle Zutaten zugeben und nochmals ca. 15 Sekunden kochen lassen. Eine Minute stehen lassen. Milch in einem Topf erwärmen. Tee in Tassen filtern. Milch und Zucker hinzufügen. Servieren.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Porta ad ebollizione 2 tazze d'acqua.\r\nAggiungere tutti gli ingredienti e far bollire di nuovo per circa 15 secondi.\r\nLascia riposare per un minuto.\r\nLatte caldo in una pentola.\r\nFiltra il tè in tazze.\r\nAggiungere il latte e lo zucchero.\r\nQuesto è tutto.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/uyrpww1441246384.jpg",
    strIngredient1: "Water",
    strIngredient2: "Tea",
    strIngredient3: "Ginger",
    strIngredient4: "Cardamom",
    strIngredient5: "Cloves",
    strIngredient6: "Cinnamon",
    strIngredient7: "Black pepper",
    strIngredient8: "Sugar",
    strIngredient9: "Milk",
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2 cups ",
    strMeasure2: "3-4 tsp ",
    strMeasure3: "1 chunk dried ",
    strMeasure4: "3-4 crushed ",
    strMeasure5: "3 ",
    strMeasure6: "1 piece ",
    strMeasure7: "1-2 whole ",
    strMeasure8: " to taste\n",
    strMeasure9: "to taste",
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2015-09-03 03:13:04",
  },
  {
    idDrink: "11121",
    strDrink: "Bobby Burns Cocktail",
    strDrinkAlternate: null,
    strTags: null,
    strCategory: "Ordinary Drink",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Stir all ingredients (except lemon peel) with ice and strain into a cocktail glass. Add the twist of lemon peel and serve.",
    strInstructionsES:
      "Remover todos los ingredientes (excepto la piel de limón) con hielo y colar en una copa de cóctel. Añadir el twist de piel de limón y servir.",
    strInstructionsDE:
      "Alle Zutaten (außer Zitronenschale) mit Eis verrühren und in ein Cocktailglas abseihen. Die Zitronenschale hinzufügen und servieren.",
    strInstructionsFR:
      "Mélanger tous les ingrédients (sauf le zeste de citron) avec de la glace et filtrer dans un verre à cocktail. Ajouter le zeste de citron et servir.",
    strInstructionsIT:
      "Aggiungere la scorza di limone e servire.Mescolare tutti gli ingredienti (tranne la buccia di limone) con ghiaccio e filtrare in una coppetta da cocktail.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/km6se51484411608.jpg",
    strIngredient1: "Sweet Vermouth",
    strIngredient2: "Scotch",
    strIngredient3: "Benedictine",
    strIngredient4: "Lemon peel",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 1/2 oz ",
    strMeasure2: "1 1/2 oz ",
    strMeasure3: "1 1/4 tsp ",
    strMeasure4: "1 twist of ",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2017-01-14 16:33:28",
  },
  {
    idDrink: "12758",
    strDrink: "Gagliardo",
    strDrinkAlternate: null,
    strTags: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Shake well and serve in a cocktail glass. This is a home cocktail of American/Internet Bar del Pozzo, Pavia, Italy.",
    strInstructionsES:
      "Agitar bien y servir en copa de cóctel. Este es un cóctel casero de American/Internet Bar del Pozzo, Pavia, Italia.",
    strInstructionsDE:
      "Gut schütteln und in einem Cocktailglas servieren. Dies ist ein Cocktail aus American/Internet Bar del Pozzo, Pavia, Italien.",
    strInstructionsFR:
      "Bien agiter et servir dans un verre à cocktail. Il s'agit d'un cocktail maison de l'Américain/Internet Bar del Pozzo, Pavie, Italie.",
    strInstructionsIT:
      "Shakerare bene e servire in una coppetta da cocktail.Questo è un cocktail casalingo dell'American / Internet Bar del Pozzo, Pavia, Italia.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/lyloe91487602877.jpg",
    strIngredient1: "Peach Vodka",
    strIngredient2: "Lemon juice",
    strIngredient3: "Galliano",
    strIngredient4: "Sirup of roses",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "5 parts ",
    strMeasure2: "3 parts ",
    strMeasure3: "1 part ",
    strMeasure4: "1 part ",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2017-02-20 15:01:18",
  },
  {
    idDrink: "11014",
    strDrink: "Alexander",
    strDrinkAlternate: null,
    strTags: "IBA,Classic,Dairy",
    strCategory: "Ordinary Drink",
    strIBA: "Unforgettables",
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Shake all ingredients with ice and strain contents into a cocktail glass. Sprinkle nutmeg on top and serve.",
    strInstructionsES:
      "Agite todos los ingredientes con hielo y cuele el contenido en una copa de cóctel. Espolvorear nuez moscada por encima y servir.",
    strInstructionsDE:
      "Alle Zutaten mit Eis schütteln und in ein Cocktailglas abseihen. Muskatnuss darüber streuen und servieren.",
    strInstructionsFR:
      "Secouer tous les ingrédients avec de la glace et filtrer le contenu dans un verre à cocktail. Saupoudrer de noix de muscade et servir.",
    strInstructionsIT:
      "Shakerare tutti gli ingredienti con ghiaccio e filtrare il contenuto in un bicchiere da cocktail. Cospargere di noce moscata e servire.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/0clus51606772388.jpg",
    strIngredient1: "Gin",
    strIngredient2: "Creme de Cacao",
    strIngredient3: "Light cream",
    strIngredient4: "Nutmeg",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1/2 oz ",
    strMeasure2: "1/2 oz white ",
    strMeasure3: "2 oz ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    dateModified: "2016-11-04 09:50:39",
  },
];

const HomePage: React.FC = () => {
  return (
    <div className="min-h-screen bg-stone-50">
      <CocktailBord cocktails={initialCocktails} />
    </div>
  );
};

export default HomePage;
